1. Import NumPy as np


In [1]:
import numpy as np

2. Create an array of 10 zeros

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create an array of 10 ones

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Create an array of 10 fives

In [4]:
np.linspace(5, 5, 10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Create an array of the integers from 10 to 50

In [7]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. Create an array of all the even integers from 10 to 50

In [8]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. Create a 3x3 identity matrix

In [14]:
np.identity(3) #np.eye(3) ile de yapilabilir.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. Use NumPy to generate a random number between 0 and 1
random.rand() fonksiyonu, belirtilen boyutta bir veya birden fazla boyutlu bir dizi oluşturarak belirli bir dağılıma göre rastgele sayılar üretir. Bu fonksiyon, belirtilen boyutlarda 0 ile 1 arasında uniform (düzgün) dağılımlı rastgele sayılar üretir.

Örneğin, np.random.rand() çağrısı tek bir rastgele sayı üretir ve bu sayı 0 ile 1 arasındadır. Bu, 0 dahil, 1 hariç bir değer olacaktır.

In [21]:
random_number = np.random.rand()
print(random_number)

0.42344446247029743


10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
random.randn() fonksiyonu, belirtilen boyutta bir veya birden fazla boyutlu bir dizi oluşturarak standart normal dağılıma göre rastgele sayılar üretir. Standart normal dağılım, ortalaması (mean) 0 ve standart sapması (standard deviation) 1 olan bir normal dağılımdır.

Örneğin, np.random.randn(25) çağrısı 25 adet rastgele sayı üretir, bu sayılar standart normal dağılıma göre seçilir. Yani, bu rastgele sayılar 0'a yakın olan ve normal dağılıma sahip olacaklardır, yani genellikle 0'a yakın olan daha fazla sayı elde edilir ve daha büyük veya daha küçük değerler daha az olasılıkla elde edilir.

In [22]:
np.random.randn(25)

array([ 0.08087027,  0.23846696,  1.59969589, -0.48109877, -0.9385352 ,
        0.81654906, -1.10321399,  0.50626966,  1.24108091,  0.06929857,
        0.55295443, -0.87558958, -0.45557198,  1.37028486, -1.34845037,
        1.77234192,  1.02822068,  1.36948152, -0.47816199, -0.0405957 ,
       -2.18097642,  0.06483806, -0.10713709, -0.80066545, -0.90303515])

11. Create the following matrix:

In [28]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Create an array of 20 linearly spaced points between 0 and 1:
Bu kod, 0 ile 1 arasında (0 ve 1 dahil olmak üzere) lineer olarak eşit aralıklı 20 noktadan oluşan bir diziyi oluşturur.

Yani, 0 ile 1 arasındaki bu aralığı 20 eşit parçaya böler ve her parçanın başlangıçtan sona doğru olan uzaklığı aynı olacak şekilde 20 nokta oluşturur. Bu noktalar, lineer bir şekilde artar.

Örneğin, çıktı şu şekilde olacaktır:

In [27]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

13. Write code that reproduces the output shown below.

14. Write code that reproduces the output shown below.

15. Write code that reproduces the output shown below.

16. Write code that reproduces the output shown below.

17. Write code that reproduces the output shown below.

18. Get the sum of all the values in mat

19. Get the standard deviation of the values in mat

20. Get the sum of all the columns in mat

Bonus Question

We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers?

In [ ]:
np.random.seed(42)